language: swift
osx_image: xcode10.2
before_install:
  - pod repo update
script:
  - ./travis-build.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - nilit.danan@kaltura.com
      - gilad.nadav@kaltura.com
    on_success: change
    on_failure: always
